#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if git diff --cached --name-only | grep -q -E '^www/'; then
    echo "Changes in 'www' directory detected"
    cd www
    pnpm run format && pnpm run lint && pnpm run test:unit
else
    echo "No changes in 'www' directory"
fi
